### PR TITLE
Add identity provider index to key derivation paths

### PR DESCRIPTION
**Pull request by orhoj**
## Purpose
Update the `key_derivation` library to pre-fix paths with the `identity provider index`. The purpose of doing this is to ensure that keys will not be used multiple times across different identity providers, i.e. the keys are isolated per identity provider.

## Changes
- Updated `key_derivation` methods to require the index of an identity provider.
- Added official test vectors for `words_to_seed` function in `key_derivation`.
- Updated rust-bins to work with the new library.
- Updated mobile_wallet to work with the new library.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Review by abizjak — COMMENTED** [review]
I guess the test vectors are compared to what the ledger/web wallet does?

We need to update the version of both `user_cli` and the `client` tool. The `user_cli` is versioned in `user_cli.rs` using `structopt`/`clap` versioning support. Can you please do that?

**Comment by orhoj** [comment]
> I guess the test vectors are compared to what the ledger/web wallet does?
> 
> We need to update the version of both `user_cli` and the `client` tool. The `user_cli` is versioned in `user_cli.rs` using `structopt`/`clap` versioning support. Can you please do that?

The test vectors are generated from a Typescript implementation I have that does the same thing. The plan is to have the same tests for the Ledger when we implement it there, but we haven't yet. I should probably add those tests before we release the mobile wallets / browser wallet to ensure that everything is consistent.

I will bump the versions a minor.

**Review by eb-concordium — APPROVED** [review]
Looks good.

**Review by chrmatt — APPROVED** [review]
Looks good.

**Review by abizjak — APPROVED** [review]

**Pull request merged**
