### PR TITLE
Print the entire genesis in the genesis tool.

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Make the genesis tool output the entire genesis.

Example output: [genesis-block.txt](https://github.com/Concordium/concordium-base/files/6397777/genesis-block.txt)

## Changes

- Output the parts of genesis that was not yet printed.
- Try to pretty print as much as possible.
- Modify Show instances of UpdateKeysThreshold and AccountThreshold to simply print the number.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

### CODE REVIEW

**Comment by td202** [comment]
The access structures for the baker stake threshold, adding anonymity revokers, and adding identity providers need to be added.

**Comment by td202** [comment]
It would probably also be worth printing the genesis block hash. It might be nice to have a "summary" mode that doesn't print out all of the cryptographic values.

**Comment by abizjak** [comment]
> It would probably also be worth printing the genesis block hash. It might be nice to have a "summary" mode that doesn't print out all of the cryptographic values.

I added printing of the hash.

For some use-cases it might be useful to have a summary mode, but for the genesis ceremony it is very important that those cryptographic values are also checked. If you don't have line-wrapping enabled they are pretty unobtrusive as well.

I don't think it makes sense to spend much time on this.

**Review by td202 — APPROVED** [review]
I have checked, and it appears to me that this indeed prints all of the genesis data.

**Review by tschudid — COMMENTED** [review]
Looks good.

**Pull request merged**
