### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Add documentation to exported definitions from the id and common libraries.

## Changes

- add documentation
- move AttributeKind from ffi to constants where it more properly belongs. The reason it was in ffi is a historical accident in that that was the first place it was needed, but now it is used extensively by all instantiations of the id library, so it should be in constants together with other fixed parameters.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by abizjak** [comment]
@shjortConcordium would you mind going through this PR and checking whether these changes break anything on your end (that is not easily fixable)? I don't think they should, but it is better to be safe. :)

**Comment by shjortConcordium** [comment]
> @shjortConcordium would you mind going through this PR and checking whether these changes break anything on your end (that is not easily fixable)? I don't think they should, but it is better to be safe. :)

I have checked, and it does not break anything (that isn't fixed by adjusting the imports).

**Comment by abizjak** [comment]
> > @shjortConcordium would you mind going through this PR and checking whether these changes break anything on your end (that is not easily fixable)? I don't think they should, but it is better to be safe. :)
> 
> I have checked, and it does not break anything (that isn't fixed by adjusting the imports).

Can you do a proper review then and approve the changes, or insert comments if you have them?

**Review by shjortConcordium — COMMENTED** [review]
Looked it over, found some small errors.

**Comment by abizjak** [comment]
> Looked it over, found some small errors.

Thanks. I applied your suggestions.

**Review by shjortConcordium — APPROVED** [review]

**Pull request merged**
